adding json lint check

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -4,7 +4,7 @@ python:
   - "2.7"
 install:
   - "pip install --allow-all-external -r requirements.txt"
-  - "sudo apt-get install -y npm"
+  - "sudo apt-get install -y npm python-demjson"
   - "sudo npm install -g js-yaml"
 script:
   - |
@@ -12,6 +12,14 @@ script:
       js-yaml $yml >/dev/null
       if [[ $? -ne 0 ]]; then
         echo "ERROR parsing $yml"
+        exit 1
+      fi
+    done
+  - |
+    for json in $(find . -name "*.json"); do
+      jsonlint $json
+      if [[ $? -ne 0 ]]; then
+        echo "ERROR parsing $json"
         exit 1
       fi
     done
