Add a jinja2 syntax checker for Travis

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -24,6 +24,16 @@ script:
       fi
     done
   - |
+    pushd playbooks
+    for j2 in $(find ../ -name "*.j2" -o -name "*.yml"); do
+      python ../util/jinja_check.py $j2
+      if [[ $? -ne 0 ]]; then
+          echo "Jinja parsing error on $j2"
+          exit 1
+      fi
+    done
+    popd
+  - |
     set -e
     cd playbooks/edx-east
     ROLE_DIRS=$(/bin/ls -d roles/*)
